# Generated by Django 5.0.3 on 2024-03-31 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.neighborhood'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.locality'),
        ),
    ]
