# Generated by Django 5.0.3 on 2024-03-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_addresses_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localities',
            new_name='Locality',
        ),
    ]
