# Generated by Django 5.0.3 on 2024-07-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address_id',
            new_name='address',
        ),
    ]
